name: Matrix Configuration

on:
    #push:
    workflow_dispatch:

env:
    NAME: "James"
    SURNAME: "Bond"
    ALIAS: "Mr"
    NICKNAME: "007"

jobs:
    deploy:
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hello-world, alpine]
            exclude:
              - images: alpine
                os: windows-latest
            include:
              - images: amd64/alpine
                os: ubuntu-20.04
        timeout-minutes: 1
        runs-on: ${{ matrix.os }}
        steps:
            - name: Run Images
              run: docker run ${{ matrix.images }}
              
            - name: Greetings
              run: |
                echo "My name is ${{ env.SURNAME }}"
                sleep 2
                echo "${{ env.NAME }} ${{ env.SURNAME }}"
            
            - name: Welcome
              run: |
                echo "Hello ${{ env.ALIAS}} ${{ env.SURNAME }}"
                sleep 2
                echo "Nice to see you ${{ env.NICKNAME }}"
