name: Exploring Variables and Secrets

on:
    #push
    workflow_dispatch: 

env:
    NAME: "John"
    SURNAME: "Doe"

jobs:
    firstname:
        runs-on: ubuntu-latest
        steps:
            - name: Echo first name
              run: echo "Hello ${{ env.NAME }}"

            - name: Sleep 5
              run: sleep 5
    
    fullname:
        if: github.ref == 'refs/heads/main'
        needs: firstname
        concurrency:
            group: production-deployment
            cancel-in-progress: false
        runs-on: ubuntu-latest
        steps:
            - name: Echo fullname
              timeout-minutes: 1
              run: |
                echo "Hello ${{ env.NAME}} ${{ env.SURNAME}}"
                sleep 600
                echo "EH EH-EH"

