name: Exploring Variables and Secrets

on:
    #push
    workflow_dispatch: 

env:
    NAME: "John"
    SURNAME: "Doe"

jobs:
    firstname:
        runs-on: ubuntu-latest
        steps:
            - name: Echo first name
              run: echo "Hello ${{ env.NAME }}"

            - name: Sleep 5
              run: sleep 5
    
    fullname:
        runs-on: ubuntu-latest
        steps:
            - name: Echo fullname
              run: echo "Hello ${{ env.NAME}} ${{ env.SURNAME}}"
            
            - name: Sleep 5
              run: sleep 5